version: '3.8'

services:
  db:
    image: postgres:16
    container_name: plant-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: plantdb
    ports:
      - "5432:5432"
    restart: always