# PostgreSQL adatbázis kapcsolat
spring.datasource.url=jdbc:postgresql://localhost:5432/plantdb
spring.datasource.username=postgres
spring.datasource.password=password

# Hibernate beállítások (automatikusan létrehozza a táblákat)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# A H2 konzolt kikapcsoljuk, mert már nincs rá szükség
spring.h2.console.enabled=false